### ISSUE TITLE
nmake missing

### ISSUE THREAD

**Issue by tonka3000** [lasote/conan-openssl#13]
If i build this package on Windows (msvc2010 x64) i've get an error that nmake is missing (because it is not in the path variable). Is it possible that conan call the init file ("C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat"" x86_amd64) for me internally, because otherwise it is very hard to build.

**Comment by lasote** [comment]
I've solved in 1.0.2i and uploading packages for new 1.0.2j (fixed too).
