### ISSUE TITLE
Incompatibility with Python 3.x at least on Windows

### ISSUE THREAD

**Issue by torbjoernk** [lasote/conan-openssl#17]
The `conanfile.py` is incompatible with Python 3.x at least on Windows. The following `dict#iteritems()` makes problems in `build()#windows_make()`:

https://github.com/lasote/conan-openssl/blob/release/1.0.2j/conanfile.py#L189-L194
```python
# Rename libs with the arch
renames = {"./binaries/lib/libeay32.lib": "./binaries/lib/libeay32%s.lib" % runtime,
           "./binaries/lib/ssleay32.lib": "./binaries/lib/ssleay32%s.lib" % runtime}
for old, new in renames.iteritems():
    if os.path.exists(old):
        os.rename(old, new)
```
`dict#itermitems()` was removed from Python 3.x in favour of `dict#items()`.

**Comment by lasote** [comment]
Sorry for the delay. It's solved, thanks for reporting.

**Comment by barcharcraz** [comment]
Where is it fixed? I still see iteritems in the code and 1.0.2k does not compile on windows with python3 for me.

**Comment by lasote** [comment]
Sorry I patched it in other branch but not the 1.0.2k.
Now it should be ok. Please try it and close the issue if its ok.

**Comment by jeremyong** [comment]
Still broken on windows

**Comment by jeremyong** [comment]
This is broken in pretty much every branch I can find. I was looking to conan itself as a possible cross-platform package manager but literally failing at the tutorial (which has you install poco 1.7) and needing to dig up this issue isn't inspiring a ton of confidence.

**Comment by barcharcraz** [comment]
openssl is kinda a drag to build on pretty much any platform.

**Comment by lasote** [comment]
@jeremyong in the 1.0.2k is ok, both the branch and the stable recipe in the central repository. If it's failing in another line please report it.

About the fails and the tutorial, sorry to hear that, we try to maintain some recipes like the OpenSSL one but it's hard sometimes. But please, understand that Conan IS NOT my sometimes buggy recipes, you could even fork the recipe repository, fix it, export the recipe to your channel and override the dependency in the consumer side. That is a good value of conan. And it has many many other, if the tutorial failed for you, try to keep reading and see if it fits with your use case, the getting started is just a general example to show the very basics of conan.

Also please understand that almost every month new compiler versions are released, it's very common that we don't update the latest binaries for every new compiler version.

And about all of this, we created the conan-center repository on Bintray where we only will include recipes with quality and guarantee of maintenance. Now is empty, but the community will fill it soon.

I'll try to fix more branches of openssl.

**Comment by lasote** [comment]
1.0.2i fixed! Hope it helps with the tutorial and py3
