### ISSUE TITLE
Whitespaces & build failure

### ISSUE THREAD

**Issue by Kaosumaru** [lasote/conan-openssl#2]
I have spaces in my username, so those lines:

    config_options_string += " --with-zlib-include=" + include_path
    config_options_string += " --with-zlib-lib=" + lib_path

Are building incorrect arguments, since paths are unquoted (maybe they should be quoted by default?)

**Comment by lasote** [comment]
Thanks, I have quoted those values. Try it now and tell me if it works! :+1: 

Remember to replace the conanfile.py of the package, you can:

Option 1: Clone this repository and execute "conan export lasote/stable" to override the old conanfile.py in your registry

Option 2: Delete all OpenSSL package in your computer and start again with conan install: "conan remove Openssl*" "conan install "

**Comment by Kaosumaru** [comment]
OK, I've tried and it seems to be working now, I've successfully compiled OpenSSL (at least I think so, I haven't linked resulting binary yet). But it looks that still are some small issues with unquoted paths, I've got few warnings during compilation:

    cl : Command line warning D9024 : unrecognized source file type '[surname]\.conan\data\zlib\1.2.8\lasote\stable\package\78f4112796f7cf1aa09e62d47afde489b889213c\include', object file assumed
    cl : Command line warning D9027 : source file '[surname]\.conan\data\zlib\1.2.8\lasote\stable\package\78f4112796f7cf1aa09e62d47afde489b889213c\include' ignored

From the looks of it, Include directory passed to cl is cut in half.

**Comment by lasote** [comment]
OK. I will take another look. Could you post your default settings? Paste here the .conan/settings.yml from your user home directory.

Thanks!

**Comment by lasote** [comment]
Sorry, I mean default settings in conan.conf

**Comment by Kaosumaru** [comment]
Here you go
[conan.txt](https://github.com/lasote/conan-openssl/files/52970/conan.txt)

I've been building openSSL with build_type=Debug, if that's any difference.

But it looks for me like it's ~~OpenSSL~~ perl's fault. OK, now i know what is wrong...

**Comment by Kaosumaru** [comment]
Apparently calling any perl script with `--option="aaa bbb"` doesn't work as indented, and arguments in `@ARGV` look like `[ '--option=aaa bbb' ]`. It's recognized as one argument, but quotation marks are stripped. It seems that calling it like this `--option="\"aaa bbb\"" may do the trick.

**Comment by lasote** [comment]
Hi @Kaosumaru Sorry for the delay but I have a lot of work with conan and I need a little help with this.
I understand what you told me about perl, Could you try it and send me a PR?

1. Clone this repository:
2. Modify the conanfile.py and export it to your user/channel:

    $ conan export kaosumaruael/testing

3. Change the requirement in your project to your own channel:

    [requires]
    OpenSSL/1.0.2d@kaosumaruael/testing

4. Try to build it with your modifications, remember to export the conanfile after build.

If you solve the bug you can send me a Pull Request and/or upload the conanfile.py and the generated packages to your own user account if you want! I do not pretend to be the owner of any conan package, would be great in the future if the community do it.

Thank you very much and sorry for not having too much time.

**Comment by Kaosumaru** [comment]
No problem. I've tried that, compilation worked fine, until one file exploded. Apparently, OpenSSL doesn't supports quotation marks in compiler options - one autogenerated macro will blow up. So this is pretty pointless approach. I'll think I try to file bug request to openSSL, maybe I can provide them a patch that will be accepted and not cause Heartbleed 2.0. But with such small issue, I will be probably ignored ;)

So, maybe a feature request for custom path to conan (if this isn't already possible) would be a good idea? (either way, not setting account name with space in it would be a good idea for me, it seems...)

**Comment by lasote** [comment]
Yes! you can change the storage path in ~/.conan/conan.conf

    [storage]
    # This is the default path, but you can write your own
    path: ~/.conan/data

Just change **~/.conan/data** to maybe **c:\conan_data**. You can move the data directory contents for keep data.

Thanks @Kaosumaru
