### ISSUE TITLE
Conditional requirements

### ISSUE THREAD

**Issue by memsharded** [lasote/conan-openssl#22]
Conditional requirements must be implemented in ``requirements()`` method not in configure:
```python
    def configure(self):
        del self.settings.compiler.libcxx

    def requirements(self):
        if not self.options.no_electric_fence and self.settings.os == "Linux":
            self.requires.add("electric-fence/2.2.0@lasote/stable", private=True)
        else:
            if "electric-fence" in self.requires:
                del self.requires["electric-fence"]

        if not self.options.no_zlib:
            self.requires.add("zlib/1.2.11@lasote/stable", private=False)
        else:
            if "zlib" in self.requires:
                del self.requires["zlib"]
```
This can cause issues for users that are using version_ranges. Reported for **1.0.2k** but might affect other versions

**Comment by lasote** [comment]
Fixed in 1.0.2j and 1.0.2k recipes

**Comment by jonico** [comment]
@lasote: Is this issue the reason why I cannot install libcurl without ssl support: https://github.com/lasote/conan-libcurl/blob/release/7.50.3/conanfile.py#L50

**Comment by lasote** [comment]
@jonico what is the issue? are you specifying with_openssl=False ?

**Comment by jonico** [comment]
@lasote: I tried to build with ```libcurl:with_openssl=False```

**Comment by lasote** [comment]
@jonico, got it. Try now, I've updated the recipe in conan.io. Use install -u to update your local recipe or delete it first.

**Comment by jonico** [comment]
@lasote: thanks, works now 🎉
