### ISSUE TITLE
OpenSSL 1.1.x stable anytime soon?

### ISSUE THREAD

**Issue by claasd** [lasote/conan-openssl#39]
Hi,

will there be a release of OpenSSL 1.1.x on conan-community anytime soon?

Thanks,
Claas

**Comment by lasote** [comment]
Sorry, I tried to adapt the 1.0.2 branch to build the 1.1.x but it fails in some points and I don't have time enough to achieve it. Maybe @bincrafters organization could help with this?

**Comment by lasote** [comment]
I released the 1.1.0g branch, all working pretty well apparently.
