### ISSUE TITLE
conan install with --build fails on mac

### ISSUE THREAD

**Issue by ksophocleous** [lasote/conan-openssl#4]
Hi,

I tried `conan install OpenSSL/1.0.2d@lasote/stable --build` on OSX 10.11.1 and got an error

> WARN: Forced build from source: "OpenSSL/1.0.2d@lasote/stable"
> Configuring sources in /Users/ksophocleous/.conan/data/OpenSSL/1.0.2d/lasote/stable/source
> Downloading https://www.openssl.org/source/openssl-1.0.2d.tar.gz
> Percent: [########################################] 100.0% of 5.0Mb Done...
> ERROR: OpenSSL: 'module' object has no attribute 'check_sha256'

let me know if you need any more info from me for this

**Comment by lasote** [comment]
Hi. Its my fault. I used conan 0.5 but its not public yet. I hope we release it today. I will try to remove this line if we finally dont release today.
Thanks for notice it and sorry

**Comment by lasote** [comment]
I uploaded again the openssl recipe with this line commented. Remove local copy (conan remove OpenSSL*) and try again!.

For any doubt or question just write me and enjoy conan!

**Comment by ksophocleous** [comment]
works perfectly, thank you!
