### ISSUE TITLE
makedepend required for building on linux

### ISSUE THREAD

**Issue by RobertUlbrich** [lasote/conan-openssl#41]
Using 1.0.2m seems to have introduced a new? build_requirement: makedepend 

OpenSSL/1.0.2m@conan/stable: Building your package in /var/lib/jenkins/.conan/data/OpenSSL/1.0.2m/conan/stable/build/97d86c8726f8c2170cb8e716523c629c8c27dbf0
OpenSSL/1.0.2m@conan/stable: Copying sources to build folder
OpenSSL/1.0.2m@conan/stable: Generator txt created conanbuildinfo.txt
OpenSSL/1.0.2m@conan/stable: Calling build()
OpenSSL/1.0.2m@conan/stable: Activated option! no_asm
OpenSSL/1.0.2m@conan/stable: Activated option! no_zlib
OpenSSL/1.0.2m@conan/stable: Activated option! shared
OpenSSL/1.0.2m@conan/stable: WARN: ./Configure  no-asm no-zlib shared -fPIC linux-armv4  -s
..............................................................................................................................................................................................................................................................................................................................................................OpenSSL/1.0.2m@conan/stable:  
..../util/domd: 33: ../util/domd: makedepend: not found
mv: cannot stat 'Makefile.new': No such file or directory
make[1]: *** [local_depend] Error 127
..make: *** [depend] Error 1
.OpenSSL/1.0.2m@conan/stable: 
OpenSSL/1.0.2m@conan/stable: ERROR: Package '97d86c8726f8c2170cb8e716523c629c8c27dbf0' build failed
OpenSSL/1.0.2m@conan/stable: WARN: Build folder /var/lib/jenkins/.conan/data/OpenSSL/1.0.2m/conan/stable/build/97d86c8726f8c2170cb8e716523c629c8c27dbf0
ERROR: OpenSSL/1.0.2m@conan/stable: Error in build() method, line 102
	self.unix_build(config_options_string)
while calling 'unix_build', line 173
	self.run_in_src("make depend")
while calling 'run_in_src', line 122
	self.run(command)
	ConanException: Error 512 while executing bash -l -c -o pipefail "make depend | while read line; do printf \"%c\" .; done"

**Comment by Croydon** [comment]
https://github.com/lasote/conan-openssl/pull/34

@SSE4

**Comment by SSE4** [comment]
that's from the official instructions https://wiki.openssl.org/index.php/Compilation_and_Installation#Dependencies
however, from my experience, it builds fine without `make depend`. feel free to remove it.

**Comment by lasote** [comment]
Hi, have you tried this in 1.0.2n? is it failing?

**Comment by Croydon** [comment]
@lasote This doesn't seem to be fixed with 1.1.0g:

> OpenSSL/1.1.0g@conan/stable: ------RUNNING-------
bash -l -c -o pipefail "./Configure linux-x86_64-clang -m64 -fPIC --with-zlib-include=\"/root/.conan/data/zlib/1.2.11/conan/stable/package/8094f5147bc9378351237bfd795472578065861f/include\" --with-zlib-lib=\"/root/.conan/data/zlib/1.2.11/conan/stable/package/8094f5147bc9378351237bfd795472578065861f/lib\" | while read line; do printf \"%c\" .; done"OpenSSL/1.1.0g@conan/stable:  
OpenSSL/1.1.0g@conan/stable: ------RUNNING-------
bash -l -c -o pipefail "make depend | while read line; do printf \"%c\" .; done"

It still does something with make depend in the last step.

**Comment by Croydon** [comment]
Okay, it works somehow, but the output is still confusing..
