### ISSUE TITLE
Version '1.0.2' semantically overrides later releases

### ISSUE THREAD

**Issue by digitalcircuit** [lasote/conan-openssl#42]
## In short
* Version `1.0.2` sementically overrides newer OpenSSL releases
  * Need to rename or delete [`1.0.2`](https://bintray.com/conan-community/conan/OpenSSL%3Aconan/1.0.2%3Astable ) for [`1.0.2m`](https://bintray.com/conan-community/conan/OpenSSL%3Aconan/1.0.2m%3Astable ) and later to be picked

Criteria | Rank | Reason
---------|---------|-------------
Impact | ★★☆ *2/3* | Necessary to use semantic versioning for security updates
Risk | ★★☆ *2/3* | Breaks anyone explicitly depending on [`1.0.2`](https://bintray.com/conan-community/conan/OpenSSL%3Aconan/1.0.2%3Astable )
Intrusiveness | ★☆☆ *1/3* | No source changes, shouldn't interfere with other pull requests

## Rationale
Currently, the [OpenSSL Conan package](https://bintray.com/conan-community/conan/OpenSSL%3Aconan ) has versions [`1.0.2l`](https://bintray.com/conan-community/conan/OpenSSL%3Aconan/1.0.2l%3Astable ), [`1.0.2`](https://bintray.com/conan-community/conan/OpenSSL%3Aconan/1.0.2%3Astable ), and [`1.0.2m`](https://bintray.com/conan-community/conan/OpenSSL%3Aconan/1.0.2m%3Astable ).  However, the semantic versioning check always prefers `1.0.2` over `1.0.2X` where `X` is some letter.  This means that anyone specifying a semantic version match will always get the outdated `1.0.2` instead of the latest version.

Can the [`1.0.2` version on Conan](https://bintray.com/conan-community/conan/OpenSSL%3Aconan/1.0.2%3Astable ) be renamed or deleted so newer versions again take priority?

This may be a security issue given sometimes critical vulnerabilities fixed in OpenSSL releases.

## Example
*From the [Fuzzball MUCK project](https://github.com/fuzzball-muck/fuzzball/ ), noticed [during a recent switch to the newer package](https://github.com/fuzzball-muck/fuzzball/pull/195 ):*

**Excerpt from `conanfile.txt`**
```
[requires]
# Use compatible versions of OpenSSL accoding to semantic versioning.
# See: http://docs.conan.io/en/latest/mastering/version_ranges.html
OpenSSL/[~=1.0.2m]@conan/stable
...
```

**Appveyor build log**
```
Version range '~=1.0.2m' required by 'None' resolved to 'OpenSSL/1.0.2@conan/stable'
```
*[Full log here](https://ci.appveyor.com/project/fuzzball-muck/fuzzball/build/695#L156 )*

**Comment by lasote** [comment]
Hi! thanks for your comment.
Take a look at this issue in the Conan repository: https://github.com/conan-io/conan/issues/1791
The problem with this OpenSSL package is that "1.0.2m" is not correct semantic versioning, so Conan is not able to resolve it correctly. That's why I created the `conan alias` 1.0.2, that should be updated manually when I release a new version of OpenSSL.

**Comment by digitalcircuit** [comment]
With this information and some more recent clarification in the linked bug report, this makes sense!

At some point I might file a bug report for BinTray given it does not show any indication of aliases, leading to my initial confusion.  Only by examining the [Files tab or `conanfile.py`](https://bintray.com/conan-community/conan/OpenSSL%3Aconan/1.0.2%3Astable#files/conan/OpenSSL/1.0.2/stable/export ) is that made clear; the ["Version Publication Date"](https://bintray.com/conan-community/conan/OpenSSL%3Aconan/1.0.2%3Astable ) does not change.

Or, it might be possible to update the description of the [OpenSSL 1.0.2 release](https://bintray.com/conan-community/conan/OpenSSL%3Aconan/1.0.2%3Astable ) (i.e. where it says `This version has no description yet.`) to briefly note that it's an alias for the `1.0.2x` series.

Thank you for your time!  And pardon for my long delay in reply, I meant to get back to you earlier.

**Comment by lasote** [comment]
I added the description to the version, thanks!
