### ISSUE TITLE
Add xcode 8 builds for 1.0.2n

### ISSUE THREAD

**Issue by theirix** [lasote/conan-openssl#49]
Both xcode 8 and 9 builds, shared and non-shared are required to build a lot dependencies on CI. They are missing since https://github.com/lasote/conan-openssl/commit/c64b1a7b3f332b53620dd149430805d8449d1aef

**Comment by lasote** [comment]
Pushed to release branch. CI working

**Comment by theirix** [comment]
Thanks, works now.
