### ISSUE TITLE
Can't be built with MinGW

### ISSUE THREAD

**Issue by LB--** [lasote/conan-openssl#6]
From https://github.com/conan-io/conan/issues/215

Unfortunately [compiling OpenSSL with MinGW](https://wiki.qt.io/Compiling_OpenSSL_with_MinGW) is very non-trivial and involves using MSYS - I don't think the changes for this are going to be trivial.

I personally can live without MinGW support, so consider this a low-priority issue for now.

**Comment by qiukeren** [comment]
+1 now on windows 10 with 
```

It seems to be the first time you run conan
Auto detecting your dev setup to initialize conan.conf
Found gcc 5.1
Default conan.conf settings
        os=Windows
        arch=x86_64
        compiler=gcc
        compiler.version=5.1
        compiler.libcxx=libstdc++
        build_type=Release
*** You can change them in ~/.conan/conan.conf ***
*** Or override with -s compiler='other' -s ...s***
```

It is important to fix this because it comes from the [Conan official demo] for beginers.(http://docs.conan.io/en/latest/getting_started.html)

**Comment by Kuxe** [comment]
I too have this issue on Win10 with MinGW-W64 5.3.0. I followed the getting started (http://docs.conan.io/en/latest/getting_started.html) but ended up with:
`PS C:\Users\Kuxe\programming\cpp\mytimer\build> conan install .. --build missing
Requirements
    OpenSSL/1.0.2h@lasote/stable from conan.io
    Poco/1.7.3@lasote/stable from conan.io
    zlib/1.2.8@lasote/stable from conan.io
Packages
    OpenSSL/1.0.2h@lasote/stable:c55b5bfe2b1ae23db6b3b5951282ccd2cb689f81
    Poco/1.7.3@lasote/stable:edb959e2612d0bf0be8bd10e01a131c7a195f54e
    zlib/1.2.8@lasote/stable:cd3e418e619287a431ed81161646f9073dcb193e

ERROR: Poco/1.7.3@lasote/stable: Error in package_info() method, line 177
        if self.settings.compiler.runtime == "MT" or self.settings.compiler.runtime == "MTd":
        'settings.compiler.runtime' doesn't exist for 'gcc'
'settings.compiler' possible configurations are ['exception', 'libcxx', 'threads', 'version']
PS C:\Users\Kuxe\programming\cpp\mytimer\build>`

**Comment by lasote** [comment]
@Kuxe It's a Poco package issue, the recipe is supposing the windows users are using Visual Studio. Please open an issue there https://github.com/lasote/conan-poco I'll try to take look to it.

**Comment by lasote** [comment]
I've uploaded a new OpenSSL recipe trying to compile with MinGW but it fails.
Conan don't make miracles (yet hahah) I need to know how to compile OpenSSL with MinGW to be able to write a recipe.
Was Someone able to compile OpenSSL with MinGW? If true please, give me some tips. I putted the msys tools in the path and invoked:

```
def mingw_make(config_options_string):
        # NOT WORKING, PLEASE, ANY HELP WOULD BE GREAT.
        # WITH THE MSYS TOOLS IN THE PATH IT RUNS MAKE BUT IT FAILS
        suffix = "64" if self.settings.arch == "x86_64" else ""
        command = "perl Configure mingw%s %s" % (suffix, config_options_string)
        run_in_src(command, show_output=True)
        self.output.warn("----------MAKE OPENSSL %s-------------" % self.version)
        run_in_src("make", show_output=True)
```
It fails:

```
buildinf.h:15:9: error: missing terminating ' character
         '5','8','8','a','5','3','b','b','7','0','4','\','b','i','n','\','g','c',
         ^
```


The recipe of OpenSSL/1.0.2i will try to compile it following the above procedure: https://www.conan.io/source/OpenSSL/1.0.2i/lasote/stable

**Comment by lasote** [comment]
@Kuxe I'm generating Poco 1.7.5 packages solving the error you found, but now it crashes in the OpenSSL compilation... :( Help needed!

**Comment by rcmonitor** [comment]
Any progress on the issue?
Is there any way to compile "Hello world" on windows with MinGW by now?

**Comment by lasote** [comment]
Hi @rcmonitor 

We have released some improvements to use MinGW with autotools in windows, you can read more here: http://docs.conan.io/en/latest/howtos/migrate_to_new_environment_management.html#building-autotools-projects-in-windows-with-mingw

A hello world can be easily compiled in Windows with MinGW, just use `-s compiler=gcc` and put MinGW in the path. I also recommend you to read this blog post I wrote: http://blog.conan.io/2016/12/22/Building-multi-compiler-C_and_C++-applications-with-conan.html

I'll try again to build OpenSSL with MinGW but the compile issue doesn't seem to be related with conan but with OpenSSL build system.

**Comment by lasote** [comment]
Hi all, I've made some progress!
I've opened a PR #21 that supports MinGW. It requires a MSYS64 installed and conan >= 0.20.0.
If you want to try it, clone the repo, checkout to testing/1.0.2j and export the recipe to your local cache with:

`conan export user/channel`

Feedback is welcomed.

**Comment by letsjustfixit** [comment]
Hey everyone, 
I've been tryin to compile libcurl myself so needed openssl also
setting OpenSSL:no_asm=True seems to matter :)

**Comment by lachlankrautz** [comment]
Been trying to test the #21 build. When I build with msys and mingw64 in path cmake complains that "sh" from msys is in the path. When I build with just mingw64 in the path, much later conan fails when it tries to call run_in_windows_bash which finds no bash in the path.

Am I missing something here; it seems like there are mutually exclusive build requirements?

**Comment by lasote** [comment]
@lachlankrautz I've solved that problem with conan 0.21.0 but is not released yet. If you can try it from sources use the develop branch.

**Comment by lachlankrautz** [comment]
I was able to build mingw OpenSSL using mingw on windows 10 but I needed to change conan's "run_in_windows_bash" to use a full path to msys2's bash.

- If you have msys2/usr/bin in path then all mingw-cmake commands will fail as they abort if they detect sh in the path
- If you have activated windows feature "Windows Subsystem for Linux" then windows subsystem bash will be in the path and msys paths won't work (cd "build folder" directory not found)
- If msys2/usr/bin is not in the path cmake builds will work but auto tools builds wont

I think conan needs to search out the correct bash path ("c:/msys2/usr/bin/bash" in my case) and call bash using full path for "run_in_windows_bash" feature.

**Comment by lasote** [comment]
@lachlankrautz Thanks for the feedback, you are right. With 0.21 I only solve the point 1) In case of 2) and 3) you need to specify where bash is. I'm opening an issue in conan repository with your comments.

**Comment by lasote** [comment]
@lachlankrautz Conan 0.22 has been released. Now you can adjust the environment variable **CONAN_BASH_PATH** or the ``conan.conf`` **bash_path** variable to change the default bash location.

**Comment by lachlankrautz** [comment]
Awesome, works great.
