### ISSUE TITLE
".lib" being added when it shouldn't

### ISSUE THREAD

**Issue by fbeutel** [lasote/conan-openssl#9]
In the package_info function, it says: 
`self.cpp_info.libs = ["ssleay32" + suffix, "libeay32" + suffix, "crypt32.lib", "msi.lib"]`

In my case, when I use a project that depends on OpenSSL, this leads to the following compiler flags:
`-lssleay32MD -llibeay32MD -lcrypt32.lib -lmsi.lib`

At least when I test it with MSVC 2015, the compiler tries to link against 'crypt32.lib.lib', which it of course doesn't find.
`LINK : fatal error LNK1181: cannot open input file 'crypt32.lib.lib'`

When manually removing the '.lib' extension from the generated conanbuildinfo file, everything works fine, so I guess the '.lib' extensions for "crypt32.lib" and "msi.lib" should be removed - or are they needed in some other setup?

**Comment by lasote** [comment]
Thanks, I'm going to remove it and see if travis and appveyor complains. I think you are right and the extension should be removed.

**Comment by lasote** [comment]
Recipe uploaded and fixed! tell me if everything is ok. 
Remember to update your local recipe with conan install -u

**Comment by fbeutel** [comment]
Yes, everything works properly now.
Thanks for the quick response! :)

**Comment by lasote** [comment]
:)
